version: "3.7"


services: 
  database:
    image: postgres
    container_name: market_data
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=market
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=marketprisma
    volumes: 
      - pgdata:/data/postgres
      
  app:
    build: .
    container_name: app_market
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
      
volumes: 
  pgdata:
    driver: local
